name: Tag creation check

on:
  create:
    tags:
      - call-break
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: npm install, build, and test
      run: |
        echo 'tag creation'
      env:
        CI: true
