name: Tag creation check

on:
  create:
    branches:
      - master
    tags:
      - runTag

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: npm install, build, and test
      run: |
        echo 'tag creation runs on run tag'
      env:
        CI: true
