name: Node CI

on:
  create:
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: npm install, build, and test
      if: github.event.label.name == 'build_image' && github.event.type == 'closed'
      run: |
        echo 'runs'
      env:
        CI: true
