name: Tag creation check

on:
  create:
    branches:
      - refs/tags/tagss

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: npm install, build, and test
      run: |
        echo 'tag creation runs on run tag'
      env:
        CI: true
