name: Node CI

on:
  pull_request:
    types: [closed]
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: npm install, build, and test
      run: |
        echo 'runs'
      env:
        CI: true
