name: Node CI

on:
  pull_request:
    types: [closed, labeled]
    branches:
      - master
  label:
    type: []
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: npm install, build, and test
      if: github.event.label.name == 'build_image'
      run: |
        echo 'runs'
      env:
        CI: true
