name: Node CI

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: download json file
      run: |
        echo 'runs'
        curl https://raw.githubusercontent.com/snipper-code/resources/master/res.json -o res.json
        ls
      env:
        CI: true
